-- ============================================================
-- AM (DS1): Oracle Access View on local NYC Property Sales
-- SII-SIA19: Integrated Real Estate Market Analysis System
--
-- Federation pattern: LOCAL VIEW
-- Underlying table: FDBO.NYC_PROPERTY_SALES (loaded by 11_DS_ORCL_Schema_Sales.sql)
-- ============================================================

CREATE OR REPLACE VIEW FDBO.V_NYC_SALES AS
SELECT
    SALE_ID,
    BOROUGH_NAME,
    NEIGHBORHOOD,
    BUILDING_CLASS_CATEGORY,
    ADDRESS,
    ZIP_CODE,
    RESIDENTIAL_UNITS,
    COMMERCIAL_UNITS,
    TOTAL_UNITS,
    LAND_SQUARE_FEET,
    GROSS_SQUARE_FEET,
    YEAR_BUILT,
    SALE_PRICE,
    SALE_DATE,
    EXTRACT(YEAR  FROM SALE_DATE) AS SALE_YEAR,
    EXTRACT(MONTH FROM SALE_DATE) AS SALE_MONTH,
    TO_NUMBER(TO_CHAR(SALE_DATE, 'Q')) AS SALE_QUARTER
FROM FDBO.NYC_PROPERTY_SALES
WHERE SALE_PRICE IS NOT NULL
  AND SALE_PRICE > 0;

COMMENT ON TABLE FDBO.V_NYC_SALES IS
    'DS1 access view - NYC Department of Finance Rolling Sales (transactional fact source)';

-- ----------------------- VERIFICATION -----------------------
SELECT COUNT(*) AS NR_SALES, MIN(SALE_DATE) AS FROM_DATE, MAX(SALE_DATE) AS TO_DATE
FROM FDBO.V_NYC_SALES;

SELECT BOROUGH_NAME,
       COUNT(*) NR_SALES,
       ROUND(AVG(SALE_PRICE), 0)  AVG_PRICE,
       ROUND(MEDIAN(SALE_PRICE), 0) MEDIAN_PRICE
FROM FDBO.V_NYC_SALES
GROUP BY BOROUGH_NAME
ORDER BY NR_SALES DESC;

SELECT SALE_YEAR, SALE_QUARTER, COUNT(*) NR_SALES,
       ROUND(SUM(SALE_PRICE)/1e6, 1) TOTAL_M_USD
FROM FDBO.V_NYC_SALES
GROUP BY SALE_YEAR, SALE_QUARTER
ORDER BY SALE_YEAR, SALE_QUARTER;
