 -- AM: Oracle Internal Sales View
-- FDBO schema - Access Model

CREATE OR REPLACE VIEW FDBO.AM_SALES_VIEW AS
SELECT 
    s.SALE_ID, s.PRODUCT_ID, p.PRODUCT_NAME, p.CATEGORY,
    s.EMPLOYEE_ID, e.FIRST_NAME || ' ' || e.LAST_NAME AS EMPLOYEE_NAME,
    e.DEPARTMENT_ID, d.DEPARTMENT_NAME,
    s.CUSTOMER_ID, s.SALE_DATE, s.QUANTITY, s.UNIT_PRICE, s.TOTAL_AMOUNT
FROM SALES.SALES s
JOIN SALES.PRODUCTS p ON s.PRODUCT_ID = p.PRODUCT_ID
JOIN SALES.EMPLOYEES e ON s.EMPLOYEE_ID = e.EMPLOYEE_ID
JOIN SALES.DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID;
