-- ============================================================
-- 00_DS_ORCL_Setup.sql
-- Run as SYSTEM in SQL Developer (F5 - Run as Script).
-- Creates FDBO user, directory, all external tables, typed tables,
-- and loads all 5 NYC boroughs + macro indicators.
-- ============================================================

-- ── 1. User ──────────────────────────────────────────────────
CREATE USER FDBO IDENTIFIED BY fdbo123
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE SYNONYM TO FDBO;
GRANT CREATE TABLE, CREATE SEQUENCE, CREATE PROCEDURE TO FDBO;

-- ── 2. Directory (CSVs live here inside the container) ───────
CREATE OR REPLACE DIRECTORY EXT_FILE_DS AS '/opt/oracle/oradata/';
GRANT READ, WRITE ON DIRECTORY EXT_FILE_DS TO FDBO;

-- ── 3. External tables (one per borough) ─────────────────────
-- SKIP 5: 4 NYC metadata rows + 1 header row

CREATE TABLE FDBO.EXT_NYC_SALES_MANHATTAN (
    BOROUGH                         NUMBER,
    NEIGHBORHOOD                    VARCHAR2(60),
    BUILDING_CLASS_CATEGORY         VARCHAR2(60),
    TAX_CLASS_AT_PRESENT            VARCHAR2(4),
    BLOCK                           NUMBER,
    LOT                             NUMBER,
    EASEMENT                        VARCHAR2(20),
    BUILDING_CLASS_AT_PRESENT       VARCHAR2(4),
    ADDRESS                         VARCHAR2(120),
    APARTMENT_NUMBER                VARCHAR2(20),
    ZIP_CODE                        VARCHAR2(10),
    RESIDENTIAL_UNITS               NUMBER,
    COMMERCIAL_UNITS                NUMBER,
    TOTAL_UNITS                     NUMBER,
    LAND_SQUARE_FEET                VARCHAR2(20),
    GROSS_SQUARE_FEET               VARCHAR2(20),
    YEAR_BUILT                      NUMBER,
    TAX_CLASS_AT_TIME_OF_SALE       VARCHAR2(4),
    BUILDING_CLASS_AT_TIME_OF_SALE  VARCHAR2(4),
    SALE_PRICE                      VARCHAR2(20),
    SALE_DATE                       VARCHAR2(30)
)
ORGANIZATION EXTERNAL (
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY EXT_FILE_DS
    ACCESS PARAMETERS (
        RECORDS DELIMITED BY NEWLINE
        SKIP 5
        FIELDS TERMINATED BY ','
        OPTIONALLY ENCLOSED BY '"'
        MISSING FIELD VALUES ARE NULL
    )
    LOCATION ('rollingsales_manhattan.csv')
) REJECT LIMIT UNLIMITED;

CREATE TABLE FDBO.EXT_NYC_SALES_BROOKLYN (
    BOROUGH                         NUMBER,
    NEIGHBORHOOD                    VARCHAR2(60),
    BUILDING_CLASS_CATEGORY         VARCHAR2(60),
    TAX_CLASS_AT_PRESENT            VARCHAR2(4),
    BLOCK                           NUMBER,
    LOT                             NUMBER,
    EASEMENT                        VARCHAR2(20),
    BUILDING_CLASS_AT_PRESENT       VARCHAR2(4),
    ADDRESS                         VARCHAR2(120),
    APARTMENT_NUMBER                VARCHAR2(20),
    ZIP_CODE                        VARCHAR2(10),
    RESIDENTIAL_UNITS               NUMBER,
    COMMERCIAL_UNITS                NUMBER,
    TOTAL_UNITS                     NUMBER,
    LAND_SQUARE_FEET                VARCHAR2(20),
    GROSS_SQUARE_FEET               VARCHAR2(20),
    YEAR_BUILT                      NUMBER,
    TAX_CLASS_AT_TIME_OF_SALE       VARCHAR2(4),
    BUILDING_CLASS_AT_TIME_OF_SALE  VARCHAR2(4),
    SALE_PRICE                      VARCHAR2(20),
    SALE_DATE                       VARCHAR2(30)
)
ORGANIZATION EXTERNAL (
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY EXT_FILE_DS
    ACCESS PARAMETERS (
        RECORDS DELIMITED BY NEWLINE
        SKIP 5
        FIELDS TERMINATED BY ','
        OPTIONALLY ENCLOSED BY '"'
        MISSING FIELD VALUES ARE NULL
    )
    LOCATION ('rollingsales_brooklyn.csv')
) REJECT LIMIT UNLIMITED;

CREATE TABLE FDBO.EXT_NYC_SALES_QUEENS (
    BOROUGH                         NUMBER,
    NEIGHBORHOOD                    VARCHAR2(60),
    BUILDING_CLASS_CATEGORY         VARCHAR2(60),
    TAX_CLASS_AT_PRESENT            VARCHAR2(4),
    BLOCK                           NUMBER,
    LOT                             NUMBER,
    EASEMENT                        VARCHAR2(20),
    BUILDING_CLASS_AT_PRESENT       VARCHAR2(4),
    ADDRESS                         VARCHAR2(120),
    APARTMENT_NUMBER                VARCHAR2(20),
    ZIP_CODE                        VARCHAR2(10),
    RESIDENTIAL_UNITS               NUMBER,
    COMMERCIAL_UNITS                NUMBER,
    TOTAL_UNITS                     NUMBER,
    LAND_SQUARE_FEET                VARCHAR2(20),
    GROSS_SQUARE_FEET               VARCHAR2(20),
    YEAR_BUILT                      NUMBER,
    TAX_CLASS_AT_TIME_OF_SALE       VARCHAR2(4),
    BUILDING_CLASS_AT_TIME_OF_SALE  VARCHAR2(4),
    SALE_PRICE                      VARCHAR2(20),
    SALE_DATE                       VARCHAR2(30)
)
ORGANIZATION EXTERNAL (
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY EXT_FILE_DS
    ACCESS PARAMETERS (
        RECORDS DELIMITED BY NEWLINE
        SKIP 5
        FIELDS TERMINATED BY ','
        OPTIONALLY ENCLOSED BY '"'
        MISSING FIELD VALUES ARE NULL
    )
    LOCATION ('rollingsales_queens.csv')
) REJECT LIMIT UNLIMITED;

CREATE TABLE FDBO.EXT_NYC_SALES_BRONX (
    BOROUGH                         NUMBER,
    NEIGHBORHOOD                    VARCHAR2(60),
    BUILDING_CLASS_CATEGORY         VARCHAR2(60),
    TAX_CLASS_AT_PRESENT            VARCHAR2(4),
    BLOCK                           NUMBER,
    LOT                             NUMBER,
    EASEMENT                        VARCHAR2(20),
    BUILDING_CLASS_AT_PRESENT       VARCHAR2(4),
    ADDRESS                         VARCHAR2(120),
    APARTMENT_NUMBER                VARCHAR2(20),
    ZIP_CODE                        VARCHAR2(10),
    RESIDENTIAL_UNITS               NUMBER,
    COMMERCIAL_UNITS                NUMBER,
    TOTAL_UNITS                     NUMBER,
    LAND_SQUARE_FEET                VARCHAR2(20),
    GROSS_SQUARE_FEET               VARCHAR2(20),
    YEAR_BUILT                      NUMBER,
    TAX_CLASS_AT_TIME_OF_SALE       VARCHAR2(4),
    BUILDING_CLASS_AT_TIME_OF_SALE  VARCHAR2(4),
    SALE_PRICE                      VARCHAR2(20),
    SALE_DATE                       VARCHAR2(30)
)
ORGANIZATION EXTERNAL (
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY EXT_FILE_DS
    ACCESS PARAMETERS (
        RECORDS DELIMITED BY NEWLINE
        SKIP 5
        FIELDS TERMINATED BY ','
        OPTIONALLY ENCLOSED BY '"'
        MISSING FIELD VALUES ARE NULL
    )
    LOCATION ('rollingsales_bronx.csv')
) REJECT LIMIT UNLIMITED;

CREATE TABLE FDBO.EXT_NYC_SALES_STATENISLAND (
    BOROUGH                         NUMBER,
    NEIGHBORHOOD                    VARCHAR2(60),
    BUILDING_CLASS_CATEGORY         VARCHAR2(60),
    TAX_CLASS_AT_PRESENT            VARCHAR2(4),
    BLOCK                           NUMBER,
    LOT                             NUMBER,
    EASEMENT                        VARCHAR2(20),
    BUILDING_CLASS_AT_PRESENT       VARCHAR2(4),
    ADDRESS                         VARCHAR2(120),
    APARTMENT_NUMBER                VARCHAR2(20),
    ZIP_CODE                        VARCHAR2(10),
    RESIDENTIAL_UNITS               NUMBER,
    COMMERCIAL_UNITS                NUMBER,
    TOTAL_UNITS                     NUMBER,
    LAND_SQUARE_FEET                VARCHAR2(20),
    GROSS_SQUARE_FEET               VARCHAR2(20),
    YEAR_BUILT                      NUMBER,
    TAX_CLASS_AT_TIME_OF_SALE       VARCHAR2(4),
    BUILDING_CLASS_AT_TIME_OF_SALE  VARCHAR2(4),
    SALE_PRICE                      VARCHAR2(20),
    SALE_DATE                       VARCHAR2(30)
)
ORGANIZATION EXTERNAL (
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY EXT_FILE_DS
    ACCESS PARAMETERS (
        RECORDS DELIMITED BY NEWLINE
        SKIP 5
        FIELDS TERMINATED BY ','
        OPTIONALLY ENCLOSED BY '"'
        MISSING FIELD VALUES ARE NULL
    )
    LOCATION ('rollingsales_statenisland.csv')
) REJECT LIMIT UNLIMITED;

-- ── 4. Typed fact table ───────────────────────────────────────
CREATE TABLE FDBO.NYC_PROPERTY_SALES (
    SALE_ID                         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BOROUGH                         NUMBER,
    BOROUGH_NAME                    VARCHAR2(20),
    NEIGHBORHOOD                    VARCHAR2(60),
    BUILDING_CLASS_CATEGORY         VARCHAR2(60),
    ADDRESS                         VARCHAR2(120),
    ZIP_CODE                        VARCHAR2(10),
    RESIDENTIAL_UNITS               NUMBER,
    COMMERCIAL_UNITS                NUMBER,
    TOTAL_UNITS                     NUMBER,
    LAND_SQUARE_FEET                NUMBER,
    GROSS_SQUARE_FEET               NUMBER,
    YEAR_BUILT                      NUMBER,
    SALE_PRICE                      NUMBER,
    SALE_DATE                       DATE
);

-- ── 5. Load all 5 boroughs ────────────────────────────────────
INSERT INTO FDBO.NYC_PROPERTY_SALES
    (BOROUGH, BOROUGH_NAME, NEIGHBORHOOD, BUILDING_CLASS_CATEGORY,
     ADDRESS, ZIP_CODE, RESIDENTIAL_UNITS, COMMERCIAL_UNITS, TOTAL_UNITS,
     LAND_SQUARE_FEET, GROSS_SQUARE_FEET, YEAR_BUILT, SALE_PRICE, SALE_DATE)
SELECT BOROUGH, 'MANHATTAN', NEIGHBORHOOD, BUILDING_CLASS_CATEGORY,
       ADDRESS, ZIP_CODE, RESIDENTIAL_UNITS, COMMERCIAL_UNITS, TOTAL_UNITS,
       TO_NUMBER(REPLACE(NULLIF(TRIM(LAND_SQUARE_FEET),  '-'), ',', '')),
       TO_NUMBER(REPLACE(NULLIF(TRIM(GROSS_SQUARE_FEET), '-'), ',', '')),
       YEAR_BUILT,
       TO_NUMBER(REPLACE(NULLIF(TRIM(SALE_PRICE), '-'), ',', '')),
       TO_DATE(SUBSTR(TRIM(SALE_DATE), 1, 19), 'YYYY-MM-DD HH24:MI:SS')
FROM FDBO.EXT_NYC_SALES_MANHATTAN
WHERE TRIM(SALE_PRICE) IS NOT NULL AND TRIM(SALE_PRICE) <> '-'
  AND TO_NUMBER(REPLACE(NULLIF(TRIM(SALE_PRICE),'-'),',','')) > 0;

INSERT INTO FDBO.NYC_PROPERTY_SALES
    (BOROUGH, BOROUGH_NAME, NEIGHBORHOOD, BUILDING_CLASS_CATEGORY,
     ADDRESS, ZIP_CODE, RESIDENTIAL_UNITS, COMMERCIAL_UNITS, TOTAL_UNITS,
     LAND_SQUARE_FEET, GROSS_SQUARE_FEET, YEAR_BUILT, SALE_PRICE, SALE_DATE)
SELECT BOROUGH, 'BROOKLYN', NEIGHBORHOOD, BUILDING_CLASS_CATEGORY,
       ADDRESS, ZIP_CODE, RESIDENTIAL_UNITS, COMMERCIAL_UNITS, TOTAL_UNITS,
       TO_NUMBER(REPLACE(NULLIF(TRIM(LAND_SQUARE_FEET),  '-'), ',', '')),
       TO_NUMBER(REPLACE(NULLIF(TRIM(GROSS_SQUARE_FEET), '-'), ',', '')),
       YEAR_BUILT,
       TO_NUMBER(REPLACE(NULLIF(TRIM(SALE_PRICE), '-'), ',', '')),
       TO_DATE(SUBSTR(TRIM(SALE_DATE), 1, 19), 'YYYY-MM-DD HH24:MI:SS')
FROM FDBO.EXT_NYC_SALES_BROOKLYN
WHERE TRIM(SALE_PRICE) IS NOT NULL AND TRIM(SALE_PRICE) <> '-'
  AND TO_NUMBER(REPLACE(NULLIF(TRIM(SALE_PRICE),'-'),',','')) > 0;

INSERT INTO FDBO.NYC_PROPERTY_SALES
    (BOROUGH, BOROUGH_NAME, NEIGHBORHOOD, BUILDING_CLASS_CATEGORY,
     ADDRESS, ZIP_CODE, RESIDENTIAL_UNITS, COMMERCIAL_UNITS, TOTAL_UNITS,
     LAND_SQUARE_FEET, GROSS_SQUARE_FEET, YEAR_BUILT, SALE_PRICE, SALE_DATE)
SELECT BOROUGH, 'QUEENS', NEIGHBORHOOD, BUILDING_CLASS_CATEGORY,
       ADDRESS, ZIP_CODE, RESIDENTIAL_UNITS, COMMERCIAL_UNITS, TOTAL_UNITS,
       TO_NUMBER(REPLACE(NULLIF(TRIM(LAND_SQUARE_FEET),  '-'), ',', '')),
       TO_NUMBER(REPLACE(NULLIF(TRIM(GROSS_SQUARE_FEET), '-'), ',', '')),
       YEAR_BUILT,
       TO_NUMBER(REPLACE(NULLIF(TRIM(SALE_PRICE), '-'), ',', '')),
       TO_DATE(SUBSTR(TRIM(SALE_DATE), 1, 19), 'YYYY-MM-DD HH24:MI:SS')
FROM FDBO.EXT_NYC_SALES_QUEENS
WHERE TRIM(SALE_PRICE) IS NOT NULL AND TRIM(SALE_PRICE) <> '-'
  AND TO_NUMBER(REPLACE(NULLIF(TRIM(SALE_PRICE),'-'),',','')) > 0;

INSERT INTO FDBO.NYC_PROPERTY_SALES
    (BOROUGH, BOROUGH_NAME, NEIGHBORHOOD, BUILDING_CLASS_CATEGORY,
     ADDRESS, ZIP_CODE, RESIDENTIAL_UNITS, COMMERCIAL_UNITS, TOTAL_UNITS,
     LAND_SQUARE_FEET, GROSS_SQUARE_FEET, YEAR_BUILT, SALE_PRICE, SALE_DATE)
SELECT BOROUGH, 'BRONX', NEIGHBORHOOD, BUILDING_CLASS_CATEGORY,
       ADDRESS, ZIP_CODE, RESIDENTIAL_UNITS, COMMERCIAL_UNITS, TOTAL_UNITS,
       TO_NUMBER(REPLACE(NULLIF(TRIM(LAND_SQUARE_FEET),  '-'), ',', '')),
       TO_NUMBER(REPLACE(NULLIF(TRIM(GROSS_SQUARE_FEET), '-'), ',', '')),
       YEAR_BUILT,
       TO_NUMBER(REPLACE(NULLIF(TRIM(SALE_PRICE), '-'), ',', '')),
       TO_DATE(SUBSTR(TRIM(SALE_DATE), 1, 19), 'YYYY-MM-DD HH24:MI:SS')
FROM FDBO.EXT_NYC_SALES_BRONX
WHERE TRIM(SALE_PRICE) IS NOT NULL AND TRIM(SALE_PRICE) <> '-'
  AND TO_NUMBER(REPLACE(NULLIF(TRIM(SALE_PRICE),'-'),',','')) > 0;

INSERT INTO FDBO.NYC_PROPERTY_SALES
    (BOROUGH, BOROUGH_NAME, NEIGHBORHOOD, BUILDING_CLASS_CATEGORY,
     ADDRESS, ZIP_CODE, RESIDENTIAL_UNITS, COMMERCIAL_UNITS, TOTAL_UNITS,
     LAND_SQUARE_FEET, GROSS_SQUARE_FEET, YEAR_BUILT, SALE_PRICE, SALE_DATE)
SELECT BOROUGH, 'STATEN ISLAND', NEIGHBORHOOD, BUILDING_CLASS_CATEGORY,
       ADDRESS, ZIP_CODE, RESIDENTIAL_UNITS, COMMERCIAL_UNITS, TOTAL_UNITS,
       TO_NUMBER(REPLACE(NULLIF(TRIM(LAND_SQUARE_FEET),  '-'), ',', '')),
       TO_NUMBER(REPLACE(NULLIF(TRIM(GROSS_SQUARE_FEET), '-'), ',', '')),
       YEAR_BUILT,
       TO_NUMBER(REPLACE(NULLIF(TRIM(SALE_PRICE), '-'), ',', '')),
       TO_DATE(SUBSTR(TRIM(SALE_DATE), 1, 19), 'YYYY-MM-DD HH24:MI:SS')
FROM FDBO.EXT_NYC_SALES_STATENISLAND
WHERE TRIM(SALE_PRICE) IS NOT NULL AND TRIM(SALE_PRICE) <> '-'
  AND TO_NUMBER(REPLACE(NULLIF(TRIM(SALE_PRICE),'-'),',','')) > 0;

COMMIT;

-- ── 6. Macro indicators external + typed table ────────────────
CREATE TABLE FDBO.EXT_RE_MACRO (
    PERIOD_DATE                     VARCHAR2(12),
    MORTGAGE_30Y_RATE               NUMBER,
    CASE_SHILLER_HPI                NUMBER,
    CPI_ALL_URBAN                   NUMBER,
    FED_FUNDS_RATE                  NUMBER,
    HOUSING_STARTS_THOUSANDS        NUMBER
)
ORGANIZATION EXTERNAL (
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY EXT_FILE_DS
    ACCESS PARAMETERS (
        RECORDS DELIMITED BY NEWLINE
        SKIP 1
        FIELDS TERMINATED BY ','
        OPTIONALLY ENCLOSED BY '"'
        MISSING FIELD VALUES ARE NULL
    )
    LOCATION ('13_DS_CSV_MacroIndicators.csv')
) REJECT LIMIT UNLIMITED;

CREATE TABLE FDBO.RE_MACRO_DIM (
    PERIOD_DATE                     DATE PRIMARY KEY,
    YEAR_NO                         NUMBER,
    QUARTER_NO                      NUMBER,
    MONTH_NO                        NUMBER,
    MORTGAGE_30Y_RATE               NUMBER,
    CASE_SHILLER_HPI                NUMBER,
    CPI_ALL_URBAN                   NUMBER,
    FED_FUNDS_RATE                  NUMBER,
    HOUSING_STARTS_THOUSANDS        NUMBER
);

INSERT INTO FDBO.RE_MACRO_DIM
SELECT
    TO_DATE(PERIOD_DATE, 'YYYY-MM-DD'),
    EXTRACT(YEAR  FROM TO_DATE(PERIOD_DATE, 'YYYY-MM-DD')),
    TO_NUMBER(TO_CHAR(TO_DATE(PERIOD_DATE, 'YYYY-MM-DD'), 'Q')),
    EXTRACT(MONTH FROM TO_DATE(PERIOD_DATE, 'YYYY-MM-DD')),
    MORTGAGE_30Y_RATE, CASE_SHILLER_HPI, CPI_ALL_URBAN,
    FED_FUNDS_RATE, HOUSING_STARTS_THOUSANDS
FROM FDBO.EXT_RE_MACRO;

COMMIT;

-- ── 7. Verification ───────────────────────────────────────────
SELECT BOROUGH_NAME, COUNT(*) NR_SALES,
       ROUND(AVG(SALE_PRICE), 0)    AVG_PRICE,
       ROUND(MEDIAN(SALE_PRICE), 0) MEDIAN_PRICE
FROM FDBO.NYC_PROPERTY_SALES
GROUP BY BOROUGH_NAME
ORDER BY NR_SALES DESC;

SELECT COUNT(*) MACRO_ROWS FROM FDBO.RE_MACRO_DIM;
