-- Integration & Analytical Model - OLAP Views
-- SIA19 - Lab 4

-- DIMENSIONAL VIEWS
CREATE OR REPLACE VIEW FDBO.OLAP_DIM_CUSTS_CITIES_DEPTS AS
SELECT c.CUSTOMER_ID, c.FIRST_NAME||' '||c.LAST_NAME AS CUSTOMER_NAME,
    c.EMAIL, c.CITY_ID, loc.CITY_NAME, loc.POSTAL_CODE,
    loc.DEPARTMENT_ID, loc.COUNTRY
FROM FDBO.AM_POSTGREST_CUSTOMERS_VIEW c
JOIN FDBO.AM_JSON_MONGODB_LOCATIONS loc ON c.CITY_ID = loc.LOCATION_ID;

CREATE OR REPLACE VIEW FDBO.OLAP_DIM_DATA_CALENDAR AS
SELECT PERIOD_ID, PERIOD_NAME, AN AS YEAR, TRIMESTRU AS QUARTER,
    START_DATE, END_DATE
FROM FDBO.EXT_XLS_PERIODS;

CREATE OR REPLACE VIEW FDBO.OLAP_DIM_CUST_CTG_TO AS
SELECT c.CUSTOMER_ID, c.FIRST_NAME||' '||c.LAST_NAME AS CUSTOMER_NAME,
    cat.CATEGORY_ID, cat.CATEGORY_NAME, cat.DISCOUNT_PCT, cat.MIN_PURCHASE
FROM FDBO.AM_POSTGREST_CUSTOMERS_VIEW c
JOIN FDBO.EXT_CSV_CUSTOMER_CATEGORIES cat ON c.CATEGORY_ID = cat.CATEGORY_ID;

CREATE OR REPLACE VIEW FDBO.OLAP_DIM_CUST_CTG_EMP AS
SELECT s.SALE_ID, s.EMPLOYEE_ID, s.EMPLOYEE_NAME, s.DEPARTMENT_NAME,
    s.CUSTOMER_ID, cat.CATEGORY_NAME, cat.DISCOUNT_PCT
FROM FDBO.AM_SALES_VIEW s
JOIN FDBO.AM_POSTGREST_CUSTOMERS_VIEW c ON s.CUSTOMER_ID = c.CUSTOMER_ID
JOIN FDBO.EXT_CSV_CUSTOMER_CATEGORIES cat ON c.CATEGORY_ID = cat.CATEGORY_ID;

CREATE OR REPLACE VIEW FDBO.PRODUCTS_VIEW AS
SELECT PRODUCT_ID, PRODUCT_NAME, CATEGORY, UNIT_PRICE, STOCK_QTY
FROM SALES.PRODUCTS;

CREATE OR REPLACE VIEW FDBO.PERIODS_VIEW AS
SELECT PERIOD_ID, PERIOD_NAME, AN AS YEAR, TRIMESTRU AS QUARTER,
    START_DATE, END_DATE
FROM FDBO.EXT_XLS_PERIODS;

-- FACT VIEW
CREATE OR REPLACE VIEW FDBO.OLAP_FACTS_SALES_AMOUNT AS
SELECT s.SALE_ID, s.SALE_DATE, s.PRODUCT_ID, s.PRODUCT_NAME, s.CATEGORY,
    s.EMPLOYEE_ID, s.EMPLOYEE_NAME, s.DEPARTMENT_NAME, s.CUSTOMER_ID,
    s.QUANTITY, s.UNIT_PRICE, s.TOTAL_AMOUNT,
    c.CATEGORY_ID AS CUSTOMER_CATEGORY_ID, cat.CATEGORY_NAME,
    loc.CITY_NAME, loc.DEPARTMENT_ID,
    EXTRACT(YEAR FROM s.SALE_DATE) AS SALE_YEAR,
    EXTRACT(MONTH FROM s.SALE_DATE) AS SALE_MONTH,
    CEIL(EXTRACT(MONTH FROM s.SALE_DATE)/3) AS SALE_QUARTER
FROM FDBO.AM_SALES_VIEW s
JOIN FDBO.AM_POSTGREST_CUSTOMERS_VIEW c ON s.CUSTOMER_ID = c.CUSTOMER_ID
JOIN FDBO.EXT_CSV_CUSTOMER_CATEGORIES cat ON c.CATEGORY_ID = cat.CATEGORY_ID
JOIN FDBO.AM_JSON_MONGODB_LOCATIONS loc ON c.CITY_ID = loc.LOCATION_ID;

-- ANALYTICAL VIEWS
CREATE OR REPLACE VIEW FDBO.OLAP_VIEW_SALES_DEP_CIT_CUST AS
SELECT DEPARTMENT_NAME, CITY_NAME, CUSTOMER_ID,
    SUM(TOTAL_AMOUNT) AS TOTAL_SALES, COUNT(SALE_ID) AS NR_SALES,
    GROUPING(DEPARTMENT_NAME) AS GRP_DEPT,
    GROUPING(CITY_NAME) AS GRP_CITY,
    GROUPING(CUSTOMER_ID) AS GRP_CUST
FROM FDBO.OLAP_FACTS_SALES_AMOUNT
GROUP BY ROLLUP(DEPARTMENT_NAME, CITY_NAME, CUSTOMER_ID);

CREATE OR REPLACE VIEW FDBO.OLAP_VIEW_SALES_CALENDAR AS
SELECT SALE_YEAR, SALE_QUARTER, SALE_MONTH,
    SUM(TOTAL_AMOUNT) AS TOTAL_SALES, COUNT(SALE_ID) AS NR_SALES,
    GROUPING(SALE_YEAR) AS GRP_YEAR,
    GROUPING(SALE_QUARTER) AS GRP_QTR,
    GROUPING(SALE_MONTH) AS GRP_MONTH
FROM FDBO.OLAP_FACTS_SALES_AMOUNT
GROUP BY ROLLUP(SALE_YEAR, SALE_QUARTER, SALE_MONTH);

CREATE OR REPLACE VIEW FDBO.OLAP_VIEW_SALES_CTG_CUST_TO AS
SELECT CATEGORY_NAME, CITY_NAME,
    SUM(TOTAL_AMOUNT) AS TOTAL_SALES, COUNT(SALE_ID) AS NR_SALES,
    AVG(TOTAL_AMOUNT) AS AVG_SALE,
    GROUPING(CATEGORY_NAME) AS GRP_CTG,
    GROUPING(CITY_NAME) AS GRP_CITY
FROM FDBO.OLAP_FACTS_SALES_AMOUNT
GROUP BY CUBE(CATEGORY_NAME, CITY_NAME);

CREATE OR REPLACE VIEW FDBO.OLAP_VIEW_SALES_CTG_CUST_EMP AS
SELECT CATEGORY_NAME, DEPARTMENT_NAME, EMPLOYEE_NAME,
    SUM(TOTAL_AMOUNT) AS TOTAL_SALES, COUNT(SALE_ID) AS NR_SALES
FROM FDBO.OLAP_FACTS_SALES_AMOUNT
GROUP BY GROUPING SETS (
    (CATEGORY_NAME, DEPARTMENT_NAME, EMPLOYEE_NAME),
    (CATEGORY_NAME, DEPARTMENT_NAME),
    (CATEGORY_NAME),
    ()
);