-- ============================================================
-- AM: Oracle Access Model Views -- DS1 si DS3
-- SII-SIA19: Retail Sales Federated Analysis System
-- ============================================================
 
-- View DS1: Oracle External Table -> Retail Sales
CREATE OR REPLACE VIEW FDBO.V_RETAIL_SALES AS
SELECT
    TRANSACTION_ID,
    TO_DATE(SALE_DATE, 'YYYY-MM-DD') AS SALE_DATE,
    CUSTOMER_ID,
    GENDER,
    AGE,
    PRODUCT_CATEGORY,
    QUANTITY,
    PRICE_PER_UNIT,
    TOTAL_AMOUNT
FROM FDBO.EXT_RETAIL_SALES;
 
-- View DS3: Oracle External Table -> Sales Sample (CSV)
CREATE OR REPLACE VIEW FDBO.V_SALES_SAMPLE AS
SELECT
    ORDER_NUMBER,
    CUSTOMER_NAME,
    PRODUCT_LINE,
    QTY_ORDERED,
    PRICE_EACH,
    SALES,
    ORDER_DATE,
    COUNTRY,
    DEAL_SIZE
FROM FDBO.EXT_SALES_SAMPLE;
 
-- Test DS1
SELECT COUNT(*) FROM FDBO.V_RETAIL_SALES;
-- Expected: 1000
 
SELECT PRODUCT_CATEGORY, COUNT(*) NR, SUM(TOTAL_AMOUNT) TOTAL
FROM FDBO.V_RETAIL_SALES
GROUP BY PRODUCT_CATEGORY
ORDER BY TOTAL DESC;
 
-- Test DS3
SELECT COUNT(*) FROM FDBO.V_SALES_SAMPLE;
-- Expected: 2823
 
SELECT PRODUCT_LINE, COUNT(*) NR, ROUND(SUM(SALES),2) TOTAL
FROM FDBO.V_SALES_SAMPLE
GROUP BY PRODUCT_LINE
ORDER BY TOTAL DESC;