-- AM: External Tables pentru CSV si XLS (perioade)
-- FDBO schema - Access Model Lab 2

-- Director Oracle
CREATE OR REPLACE DIRECTORY EXT_FILE_DS AS '/opt/oracle/oradata';
GRANT READ, WRITE ON DIRECTORY EXT_FILE_DS TO FDBO;

-- External Table CSV: Categorii Clienti
CREATE TABLE FDBO.EXT_CSV_CUSTOMER_CATEGORIES (
    CATEGORY_ID   NUMBER,
    CATEGORY_NAME VARCHAR2(50),
    DISCOUNT_PCT  NUMBER(5,2),
    MIN_PURCHASE  NUMBER
)
ORGANIZATION EXTERNAL (
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY EXT_FILE_DS
    ACCESS PARAMETERS (
        RECORDS DELIMITED BY NEWLINE
        SKIP 1
        FIELDS TERMINATED BY ','
        OPTIONALLY ENCLOSED BY '"'
        MISSING FIELD VALUES ARE NULL
    )
    LOCATION ('13_DS_CSV_CustomerCategories.csv')
)
REJECT LIMIT UNLIMITED;

-- External Table CSV: Perioade
CREATE TABLE FDBO.EXT_XLS_PERIODS (
    PERIOD_ID   NUMBER,
    PERIOD_NAME VARCHAR2(20),
    AN          NUMBER,
    TRIMESTRU   NUMBER,
    START_DATE  VARCHAR2(20),
    END_DATE    VARCHAR2(20)
)
ORGANIZATION EXTERNAL (
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY EXT_FILE_DS
    ACCESS PARAMETERS (
        RECORDS DELIMITED BY NEWLINE
        SKIP 1
        FIELDS TERMINATED BY ','
        MISSING FIELD VALUES ARE NULL
    )
    LOCATION ('13_DS_XLS_Periods.csv')
)
REJECT LIMIT UNLIMITED;
